// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooUni.Data;

namespace ZooUni.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20210718171025_newnewnewnew")]
    partial class newnewnewnew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZooUni.Data.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kind")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kind = "Predator",
                            Name = "Pombercho",
                            Type = "Tiger",
                            URL = "https://www.permaculturenews.org/wp-content/uploads/2020/10/Tiger-Supermarket.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Kind = "Predator",
                            Name = "Mufasa",
                            Type = "Lion",
                            URL = "https://ewscripps.brightspotcdn.com/b8/97/543aa49f42adb4cf0e361b3f556d/t10-0078-002.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Kind = "Mammal",
                            Name = "",
                            Type = "Giraffe",
                            URL = "https://www.gannett-cdn.com/presto/2019/06/21/PKNS/6d8c357f-2dd6-4730-8d85-5eb6a481ec2a-kns-zoo-0622_BP.JPG"
                        },
                        new
                        {
                            Id = 4,
                            Kind = "Predator",
                            Name = "",
                            Type = "Bear",
                            URL = "https://www.indianapoliszoo.com/wp-content/uploads/2018/04/CROPPED_Brown_Bear-Cheryl_Wesselresizedresized.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Kind = "Mammal",
                            Name = "",
                            Type = "Elephant",
                            URL = "https://media.npr.org/assets/img/2017/01/10/elephant1_custom-14cf2c849d4a2c5aaac9d1b017f64c4adb9f04e4.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Kind = "Reptile",
                            Name = "",
                            Type = "Crocodile",
                            URL = "https://bristolzoo.org.uk/cmsassets/body/Animals-and-Attractions/Dwarf-Crocodiles/_galleryMainNew/Dwarf-Crododiles-gallery-1.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Kind = "Predator",
                            Name = "",
                            Type = "Wolf",
                            URL = "https://arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/UXEKVA33VJB6VL4ZEYDXF4NTOY.JPG"
                        },
                        new
                        {
                            Id = 8,
                            Kind = "Mammal",
                            Name = "",
                            Type = "Deer",
                            URL = "https://cdn.pixabay.com/photo/2017/05/23/10/22/deer-2336769_960_720.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Kind = "Mammal",
                            Name = "",
                            Type = "Gorilla",
                            URL = "http://cincinnatizoo.org/wp-content/uploads/2014/04/gladys_jomo-005.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Kind = "Predator",
                            Name = "",
                            Type = "Hippopotamus",
                            URL = "https://s.hdnux.com/photos/70/22/51/14756432/3/rawImage.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
